name: CI
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update && sudo apt-get install libhts-dev bcftools
      - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      - run: brew install nim
      - run: nimble test
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: brew install nim htslib bcftools
      - run: sed -i "" -e "s/nim c/nim c --passL:-Wl,-rpath,\/opt\/homebrew\/opt\/htslib\/lib/" slivar.nimble
      - run: sed -i "" -e "s/nim c/nim c --passL:-Wl,-rpath,\/opt\/homebrew\/opt\/htslib\/lib/" tests/functional-tests.sh
      - run: nimble test
